#!/bin/sh
set -e

case "$1" in
    remove|deconfigure)
        systemctl stop litestream-a2a.service >/dev/null 2>&1 || true
        systemctl disable litestream-a2a.service >/dev/null 2>&1 || true
        ;;
esac

exit 0
