#!/bin/bash
set -e

case "$1" in
    configure)
        export A2A_SKIP_GIT=1
        export A2A_SKIP_APT=1

        /usr/local/bin/deploy_website.sh
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
        ;;
esac

exit 0
