#!/usr/bin/env bash
# =============================================================================
# A2A Commerce Platform — Local Dev Stack
# =============================================================================
# Brings up a full local development stack via docker compose:
#   - a2a-gateway (this repo, built from ./Dockerfile)
#   - SQLite DBs under a docker volume (persists between restarts)
#
# Usage:
#   scripts/dev_up.sh              # build + start, follow logs
#   scripts/dev_up.sh --detach     # build + start, background
#   scripts/dev_up.sh --rebuild    # force rebuild image
#   scripts/dev_up.sh --clean      # down + remove volumes (fresh DBs)
#   scripts/dev_up.sh --down       # stop + remove containers (keep volumes)
#   scripts/dev_up.sh --logs       # tail logs
#   scripts/dev_up.sh --shell      # exec a shell inside gateway container
#   scripts/dev_up.sh --smoke      # wait-for-health + run smoke tests
#
# The script auto-creates a dev .env if one is missing, with sandbox-safe
# placeholder values (sk_test_*, random secrets). Never use these in prod.
# =============================================================================

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# ---- helpers -----------------------------------------------------------------

log() { printf '\033[1;34m[dev_up]\033[0m %s\n' "$*" >&2; }
warn() { printf '\033[1;33m[dev_up]\033[0m %s\n' "$*" >&2; }
die() { printf '\033[1;31m[dev_up]\033[0m %s\n' "$*" >&2; exit 1; }

compose() {
    if docker compose version >/dev/null 2>&1; then
        docker compose "$@"
    elif command -v docker-compose >/dev/null 2>&1; then
        docker-compose "$@"
    else
        die "docker compose not found. Install Docker Desktop or docker-compose."
    fi
}

require_docker() {
    command -v docker >/dev/null 2>&1 || die "docker is not installed"
    docker info >/dev/null 2>&1 || die "docker daemon is not running"
}

# ---- .env bootstrap ----------------------------------------------------------

ensure_env() {
    if [[ -f "$REPO_ROOT/.env" ]]; then
        return 0
    fi
    warn ".env not found — generating dev defaults (sandbox keys only)"

    # Generate random secrets (POSIX-portable)
    rand_hex() {
        if command -v openssl >/dev/null 2>&1; then
            openssl rand -hex "$1"
        else
            python3 -c "import secrets; print(secrets.token_hex($1))"
        fi
    }

    local admin_key random_hex32 random_hex64
    admin_key="dev_admin_$(rand_hex 16)"
    random_hex32="$(rand_hex 32)"
    random_hex64="$(rand_hex 64)"

    cat > "$REPO_ROOT/.env" <<ENV
# Generated by scripts/dev_up.sh — DEV/SANDBOX ONLY.
# Do NOT use these values in production.
A2A_ENV=sandbox
HOST=0.0.0.0
PORT=8000
A2A_DATA_DIR=/var/lib/a2a

# Stripe — test mode only. Replace with your own sk_test_* from
# https://dashboard.stripe.com/test/apikeys to exercise the real Stripe API.
STRIPE_API_KEY=sk_test_placeholder_replace_me
STRIPE_WEBHOOK_SECRET=whsec_placeholder_replace_me

# Auditor keys (Ed25519) — dev-only, regenerate for staging/prod
AUDITOR_PRIVATE_KEY=${random_hex32}
AUDITOR_PUBLIC_KEY=${random_hex32}

# Admin API key (for local testing of admin endpoints)
ADMIN_API_KEY=${admin_key}

# CORS — permissive for local dev
CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8000,http://127.0.0.1:3000

# Metrics access — local only
METRICS_ALLOWED_IPS=127.0.0.1,::1

# JWT signing (dev rotation key)
JWT_SIGNING_KEY=${random_hex64}
ENV

    log "Wrote $REPO_ROOT/.env (review + replace STRIPE_API_KEY before testing payments)"
    log "Admin key for local testing: $admin_key"
}

# ---- wait-for-health ---------------------------------------------------------

wait_for_health() {
    local url="http://localhost:${A2A_PORT:-8000}/v1/health"
    local max_attempts=30
    local attempt=0

    log "Waiting for gateway health at $url ..."
    until curl -fsS "$url" >/dev/null 2>&1; do
        attempt=$((attempt + 1))
        if [[ $attempt -ge $max_attempts ]]; then
            warn "Gateway did not become healthy within $((max_attempts * 2))s"
            compose logs --tail=50 gateway || true
            return 1
        fi
        sleep 2
    done

    log "Gateway is healthy."
    curl -fsS "$url" | python3 -m json.tool 2>/dev/null || curl -fsS "$url"
}

# ---- smoke tests -------------------------------------------------------------

run_smoke() {
    local base="http://localhost:${A2A_PORT:-8000}"
    log "Running smoke tests against $base ..."

    local code
    code=$(curl -s -o /dev/null -w "%{http_code}" "$base/v1/health")
    [[ "$code" == "200" ]] || die "smoke: /v1/health returned $code (expected 200)"

    code=$(curl -s -o /dev/null -w "%{http_code}" "$base/v1/pricing")
    [[ "$code" == "401" ]] || warn "smoke: /v1/pricing returned $code (expected 401 unauthenticated)"

    code=$(curl -s -o /dev/null -w "%{http_code}" "$base/.well-known/agent-card.json")
    if [[ "$code" == "200" ]]; then
        log "smoke: agent-card.json present"
    else
        warn "smoke: /.well-known/agent-card.json returned $code"
    fi

    log "Smoke tests complete."
}

# ---- command dispatch --------------------------------------------------------

cmd="${1:-up}"

case "$cmd" in
    up|"")
        require_docker
        ensure_env
        log "Starting dev stack (building if needed) ..."
        compose up --build
        ;;
    --detach|-d|detach)
        require_docker
        ensure_env
        log "Starting dev stack (detached) ..."
        compose up --build -d
        wait_for_health || die "gateway failed to become healthy"
        log "Stack running. Logs: scripts/dev_up.sh --logs"
        ;;
    --rebuild|rebuild)
        require_docker
        ensure_env
        log "Rebuilding gateway image (no cache) ..."
        compose build --no-cache gateway
        compose up -d
        wait_for_health || die "gateway failed to become healthy"
        ;;
    --clean|clean)
        require_docker
        warn "Bringing down stack AND removing volumes (all DBs will be wiped)"
        compose down -v
        log "Clean complete."
        ;;
    --down|down|stop)
        require_docker
        log "Stopping stack (volumes preserved) ..."
        compose down
        ;;
    --logs|logs)
        require_docker
        compose logs -f --tail=100
        ;;
    --shell|shell|exec)
        require_docker
        compose exec gateway /bin/bash || compose exec gateway /bin/sh
        ;;
    --smoke|smoke)
        require_docker
        wait_for_health || die "gateway not healthy"
        run_smoke
        ;;
    --help|-h|help)
        sed -n '2,21p' "$0" | sed 's/^# \{0,1\}//'
        exit 0
        ;;
    *)
        die "Unknown command: $cmd (try --help)"
        ;;
esac
